[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[branding]
name = "Preswald Project"
logo = "images/8316546.jpg"
favicon = "images/leaf.png"
primaryColor = "#F89613"

[data.demo_csv]
type = "csv"
path = "data/demo.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"